sudo: required

services:
- docker

language: php

addons:
  apt:
    packages:
    - expect

php:
- '7.0'
- '7.1'
- '7.2'
- nightly

before_script:
- sudo apt-get update
- sudo apt-get install -y expect
- docker pull evilfreelancer/docker-routeros:6.42
- docker pull evilfreelancer/docker-routeros:latest
- docker run -d -p 12223:23 -p 18728:8728 -p 18729:8729 -ti evilfreelancer/docker-routeros:6.42
- docker run -d -p 2223:23 -p 8728:8728 -p 8729:8729 -ti evilfreelancer/docker-routeros:latest
- docker ps -a
- sleep 30
- ./preconf.tcl 12223 > /dev/null || true
- ./preconf.tcl 2223 > /dev/null || true
- composer self-update
- composer install --prefer-source --no-interaction --dev

script:
- vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
